#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

refresh_or_install_file \
    /etc/skel/.config/autostart/indicator-multiload.desktop \
    "Installing desktop autostart for indicator-multiload..."

exit 0
