#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

refresh_or_install_file \
    /etc/sysctl.d/10-linux-tools.conf \
    "Installing linux-tools configuration..."

exit 0
