#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

# This broken; needs to update /etc/resolvconf.d/tail
#refresh_or_install_file \
#    /etc/resolv.conf \
#    "Installing custom resolv.conf"

refresh_or_install_files \
    /etc/NetworkManager/system-connections/ \
    "Installing custom NetworkManager connections..." \
    root root 400 # Permissions are required

exit 0
