#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

# Exit if nothing to do
exit_if_stamped $0

printinfo "Patching Unity configuration scripts..."
patch -s -d / -p1 <patches/rootfs/ubuntu.session.diff || die "Unable to patch ubuntu.session!"
patch -s -d / -p1 <patches/rootfs/unity7.conf.diff || die "Unable to patch unity7.conf!"

updated_rootfs
make_stamp $0

exit 0
