#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

printinfo Installing home directory shortcuts...
ln -sf /usr/local/src/pybombs/src /etc/skel
ln -sf /usr/local/share/gnuradio/examples /etc/skel



exit 0
