#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

refresh_or_install_file \
    /etc/skel/.bash_aliases \
    "Installing user aliases..."

refresh_or_install_file \
    /etc/skel/.octaverc \
    "Installing octave configuration..."

exit 0
