#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

refresh_or_install_file \
    /usr/local/share/gnuradio/themes/clabs.qss \
    "Installing gnuradio themes..."

exit 0
