#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

# Install pybombs from git repository
if [ ! -f $ROOTFS_SRCDIR/pybombs_legacy/.git/config ] ; then
    printinfo Installing PyBOMBS installation program...

    # Clone pybombs git repository into source dir
    cd $ROOTFS_SRCDIR || die Unable to change directory to source dir: $ROOTFS_SRCDIR!
    git clone --recursive $PYBOMBS_GITURL || die Unable to clone pybombs from $PYBOMBS_GITURL!

    # Get latest recipes
    printinfo Retrieving latest recipes database...
    cd $ROOTFS_SRCDIR/pybombs_legacy/recipes
    git pull origin master || die Unable to retrieve latest recipes database

    cd - >/dev/null

    # Patch out running volk performance test
    SRCFILE=$ROOTFS_SRCDIR/pybombs_legacy/mod_pybombs/pybombs_ops.py
    [ -f $SRCFILE ] && {
        sed -i -e '/pkg.*gnuradio/d' $SRCFILE
        sed -i -e '/Run VOLK Profile/d' $SRCFILE
        sed -i -e '/run_volk_profile.*;/d' $SRCFILE
    }

    refresh_or_install_file \
        $ROOTFS_SRCDIR/pybombs_legacy/config.dat \
        "Updating PyBOMBS with custom configuration..." \
        999 999 644

    # Adjust the make parallelism according to config-vars
    sed -i -e 's/makewidth = 2/makewidth = '$CONFIG_MAKEWIDTH'/' $ROOTFS_SRCDIR/pybombs_legacy/config.dat

    updated_rootfs
fi

exit 0
