#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

## Preinst tasks
printinfo "Executing pre-installation scripts for PyBOMBS packages."
run-parts -v --exit-on-error $SCRIPT_BINDDIR/config/pybombs.d/preinst.d

## Actual PyBOMBS install
printinfo "Launching PyBOMBS prefix initialization."
pybombs prefix init -a sys -R livesdr /usr/local

# Postinst
printinfo "Executing post-installation scripts for PyBOMBS packages."
run-parts $SCRIPT_BINDDIR/config/pybombs.d/postinst.d

## Remove build artifacts
printinfo "Removing build artifacts from source builds."
find /usr/local/src -depth -type d -name build | xargs rm -rf || die Could not remove build artifacts.

exit 0

