#!/bin/sh

### Call PyBOMBS install
/root/live/bin/do-pybombs-install gnuradio v3.7.6.1 bin/gnuradio-config-info

### Post-installation tasks
# Install freedesktop files
[ -f /usr/share/mime/packages/gnuradio-grc.xml ] || {
    /usr/local/libexec/gnuradio/grc_setup_freedesktop install || {
        echo Unable to install gnuradio freedesktop files.
        exit 1
    }
}

# Install desktop icon for GNU Radio Companion
[ -f /etc/skel/Desktop/gnuradio-grc.desktop ] || {
    mkdir -p /etc/skel/Desktop
    install -g 999 -o 999 -m 644 \
        /usr/local/share/gnuradio/grc/freedesktop/gnuradio-grc.desktop \
        /etc/skel/Desktop
}

# Install live user configuration files
[ -x /etc/skel/.gnuradio/config.conf ] || {
    install -d -o 999 -g 999 /etc/skel/.gnuradio &&
    install -g 999 -o 999 -m 644 $LIVEUB_DIR/custom/gnuradio/config.conf /etc/skel/.gnuradio &&
    install -g 999 -o 999 -m 644 $LIVEUB_DIR/custom/gnuradio/.bash_aliases /etc/skel &&
    install -g 999 -o 999 -m 644 $LIVEUB_DIR/custom/gnuradio/.octaverc /etc/skel || {
        echo Unable to install live user GNU Radio configuration files.
    }
}

# Install documentation desktop shortcut
[ -h "/etc/skel/Desktop/GNU Radio Documentation" ] || {
    ln -sf /usr/local/share/doc/gnuradio-3.7.6.1/html/index.html \
        "/etc/skel/Desktop/GNU Radio Documentation" || {
        echo Unable to install GNU Radio Documentation shortcut.
        exit 1
    }
}

# Install Guided tutorials
TUTDIR="/etc/skel/tutorials"
[ -d "$TUTDIR" ] || {
    mkdir -p "$TUTDIR"
    $PRINTINFO "Installing GNU Radio guided tutorials..."
    wget --page-requisites --convert-links --adjust-extension \
         --recursive --level=1 --no-clobber --no-directories \
         --no-host-directories \
         --reject-regex "history|rename|protect|edit|watch|news|issues|activity|Development|Sponsor|search|users|index|roadmap|gnuradio$|wiki$|Installing|projects$|login|register|repository|files$|gnuradio$" \
         --directory-prefix="$TUTDIR" \
         http://gnuradio.org/redmine/projects/gnuradio/wiki/Guided_Tutorials || {
        $PRINTERROR Failed to retrieve guided tutorials content!
        exit 1
    }

    cd /etc/skel/Desktop
    ln -s "/home/ubuntu/tutorials/Guided_Tutorials.html" .
}
