#!/bin/sh
set -o nounset
#set -x #DEBUG
. bin/chroot-functions.sh

### Call PyBOMBS install
bin/do-pybombs-install rtl-sdr d447a2e9 bin/rtl_test

### Post-installation tasks

# Install udev permissions for rtl-sdr
[ -x /etc/udev/rules.d/rtl-sdr.rules ] || {
    install -g root -o root -m 644 $LIVEUB_DIR/custom/rtl-sdr/rtl-sdr.rules /etc/udev/rules.d || {
        $PRINTERROR Unable to install rtl-sdr udev rules file!
        exit 1
    }
}

exit 0
