#!/bin/sh
set -o nounset
#set -x #DEBUG
. bin/chroot-functions.sh

### Call PyBOMBS install
bin/do-pybombs-install bladeRF 06703b23 bin/bladeRF-cli

### Post-installation tasks

# Install udev permissions for bladeRF
[ -f /etc/udev/rules.d/88-nuand.rules ] || {
    $PRINTINFO Installing udev permissions for bladeRF...
    install -g root -o root -m 644 $LIVEUB_DIR/custom/bladeRF/88-nuand.rules /etc/udev/rules.d || {
        $PRINTERROR Unable to install bladeRF udev rules file!
        exit 1
    }
}

# Install FPGA bistream files for bladeRF
NUAND_SHARE=/usr/share/Nuand/bladeRF
[ -f $NUAND_SHARE/hostedx40.rbf ] || {
    $PRINTINFO Installing FPGA bitstream files for bladeRF
    install -d -g root -o root $NUAND_SHARE
    install -g root -o root -m 644 $LIVEUB_DIR/custom/bladeRF/hostedx40.rbf $NUAND_SHARE &&
    install -g root -o root -m 644 $LIVEUB_DIR/custom/bladeRF/hostedx115.rbf $NUAND_SHARE || {
        $PRINTERROR Unable to install bladeRF FPGA bitstream files!
        exit 1
    }
}
