#!/bin/sh

GITREV=06703b23
LWR=$ROOTFS_SRCDIR/pybombs/recipes/bladeRF.lwr

# Test if bladeRF already installed, silently exit if so
[ -x $ROOTFS_PREFIX/bin/bladeRF-cli ] || {

    # Edit bladeRF recipe for desired revision
    grep gitrev $LWR
    RET=$?
    if [ $RET -ge 2 ] ; then
        echo Unable to access bladeRF pybombs recipe.
        exit 1
    fi
    if [ $RET -eq 1 ] ; then
        echo Setting git revision in bladeRF recipe
        sed -i -e '/gitbranch/a gitrev: '$GITREV $LWR
    fi

    # Execute pybombs recipe to install bladeRF
    cd $ROOTFS_SRCDIR/pybombs
    ./pybombs install bladeRF || {
        echo Unable to install bladeRF via pybombs.
        exit 1
    }

    # Clean up compilation results
    rm -rf $ROOTFS_SRCDIR/pybombs/src/bladeRF/host/build || {
        echo Unable to clean up after bladeRF compile.
        exit 1
    }

    # Remove repository history
    rm -rf $ROOTFS_SRCDIR/pybombs/src/bladeRF/.git || {
        echo Unable to clean up after bladeRF compile.
        exit 1
    }

    # Tell the system we've installed a new shared libraries
    ldconfig
}

# Install udev permissions for bladeRF
[ -x /etc/udev/rules.d/88-nuand.rules ] || {
    install -g root -o root -m 644 $LIVEUB_DIR/custom/bladeRF/88-nuand.rules /etc/udev/rules.d || {
        echo Unable to install bladeRF udev rules file.
        exit 1
    }
}

# Install FPGA bistream files for bladeRF
NUAND_SHARE=/usr/share/Nuand/bladeRF
[ -x $NUAND_SHARE/hostedx40.rbf ] || {
    install -d -g root -o root $NUAND_SHARE
    install -g root -o root -m 644 $LIVEUB_DIR/custom/bladeRF/hostedx40.rbf $NUAND_SHARE &&
    install -g root -o root -m 644 $LIVEUB_DIR/custom/bladeRF/hostedx115.rbf $NUAND_SHARE || {
        echo Unable to install bladeRF FPGA bitstream files.
        exit 1
    }
}
