#!/bin/sh
set -o nounset
#set -x #DEBUG
. bin/chroot-functions.sh

### Pre-install tasks

# Patch out -mt suffix addition
LWR=$ROOTFS_SRCDIR/pybombs/recipes/gqrx.lwr
sed -i -e 's/BOOST_SUFFIX=-mt/BOOST_SUFFIX=/' $LWR

### Call PyBOMBS install
bin/do-pybombs-install gqrx v2.3.2 bin/gqrx
