#!/bin/sh
set -o nounset
#set -x #DEBUG
. bin/chroot-functions.sh

### Call PyBOMBS install
bin/do-pybombs-install gr-air-modes 9891907e bin/modes_gui

### Post-install tasks
# Replace installed __init__.py to fix RTLDR issue
install -g root -o root -m 644 \
    $LIVEUB_DIR/custom/gr-air-modes/__init__.py \
    /usr/local/lib/python2.7/dist-packages/air_modes
