#!/bin/sh

GITREV=5d075c64
LWR=$ROOTFS_SRCDIR/pybombs/recipes/gr-dvbs2.lwr

# Test if gr-dvbs2 already installed, silently exit if so
[ -f $ROOTFS_PREFIX/include/dvbs2/api.h ] || {

    # Edit gr-dvbs2 recipe for desired revision
    grep gitrev $LWR
    RET=$?
    if [ $RET -ge 2 ] ; then
        echo Unable to access gr-dvbs2 pybombs recipe.
        exit 1
    fi
    if [ $RET -eq 1 ] ; then
        echo Setting git revision in gr-dvbs2 recipe
        sed -i -e '/gitbranch/a gitrev: '$GITREV $LWR
    fi

    # Execute pybombs recipe to install gr-dvbs2
    cd $ROOTFS_SRCDIR/pybombs
    ./pybombs install gr-dvbs2 || {
        echo Unable to install gr-dvbs2 via pybombs.
        exit 1
    }

    # Clean up compilation results
    rm -rf $ROOTFS_SRCDIR/pybombs/src/gr-dvbs2/build clean &&
    rm -rf $ROOTFS_SRCDIR/pybombs/src/gr-dvbs2/.git || {
        echo Unable to clean up after gr-dvbs2 compile.
        exit 1
    }

    # Tell the system we've installed a new shared libraries
    ldconfig
}
