#!/bin/sh

GITREV=0e81f1c9
LWR=$ROOTFS_SRCDIR/pybombs/recipes/gr-radar.lwr

# Test if gr-radar already installed, silently exit if so
[ -f $ROOTFS_PREFIX/include/radar/api.h ] || {

    # Edit gr-radar recipe for desired revision
    grep gitrev $LWR
    RET=$?
    if [ $RET -ge 2 ] ; then
        echo Unable to access gr-radar pybombs recipe.
        exit 1
    fi
    if [ $RET -eq 1 ] ; then
        echo Setting git revision in gr-radar recipe
        sed -i -e '/gitbranch/a gitrev: '$GITREV $LWR
    fi

    # Execute pybombs recipe to install gr-radar
    cd $ROOTFS_SRCDIR/pybombs
    ./pybombs install gr-radar || {
        echo Unable to install gr-radar via pybombs.
        exit 1
    }

    # Clean up compilation results
    rm -rf $ROOTFS_SRCDIR/pybombs/src/gr-radar/build &&
    rm -rf $ROOTFS_SRCDIR/pybombs/src/gr-radar/.git || {
        echo Unable to clean up after gr-radar compile.
        exit 1
    }

    # Tell the system we've installed a new shared libraries
    ldconfig
}
