#!/bin/sh
set -o nounset
#set -x #DEBUG
. bin/chroot-functions.sh

# Pre-fetch apache-thrift source
$PRINTINFO Fetching apache-thrift source code...
cd $ROOTFS_SRCDIR/pybombs
./pybombs fetch apache-thrift || {
    $PRINTERROR Unable to fetch apache-thrift via PyBOMBS!
    exit 1
}

# Patch apache-thrift source with shutdown fix
$PRINTINFO Patching apache-thrift with shutdown fix...
cd $ROOTFS_SRCDIR/pybombs/src/apache-thrift
patch -p1 < $LIVEUB_DIR/custom/gnuradio/thrift-shutdown-fix.diff || {
    $PRINTERROR Unable to patch apache-thrift source code!
    exit 1
}
