#!/bin/sh
set -o nounset
#set -x #DEBUG
. bin/chroot-functions.sh

# Patch out custom config options in recipe
LWR=$ROOTFS_SRCDIR/pybombs/recipes/bladeRF.lwr
$PRINTINFO "Removing custom config options for bladeRF in recipe"
sed -i -e '/config_opt/d' $LWR
