#!/bin/sh
set -o nounset
#set -x #DEBUG

. bin/chroot-library.sh

# Patch out custom config options in recipe
LWR=/usr/local/src/pybombs/recipes/bladeRF.lwr
printinfo Removing custom config options for bladeRF in recipe
sed -i -e '/config_opt/d' $LWR
