#!/bin/sh
set -o nounset
#set -x #DEBUG
. bin/chroot-functions.sh

# Force gnss-sdr to use libvolk for everything
LWR=/usr/local/src/pybombs/recipes/gnss-sdr.lwr
if ! grep -q ENABLE_GENERIC_ARCH $LWR ; then
    $PRINTINFO "Adding ENABLE_GENERIC_ARCH and ENABLE_OSMOSDR to gnss-sdr configuration"
    # spaces are important
    # also, config_opt must come before inherit cmake
    sed -i -e '/gitbranch:/a var config_opt = " -DENABLE_GENERIC_ARCH=ON -DENABLE_OSMOSDR=ON "' $LWR
fi
