#!/bin/sh
set -o nounset
#set -x #DEBUG

. bin/rootfs-library.sh

FILENAME=opencl_runtime_14.2_x64_4.5.0.8.tgz
URLBASE=http://registrationcenter.intel.com/irc_nas/4181
URL=$URLBASE/$FILENAME
DIRNM=pset_opencl_runtime_14.1_x64_4.5.0.8
TMPDIR=/tmp/fosphor
DESTDIR=/

# TODO: Pretty sure PyBOMBS could do this install.

# Install Intel OpenCL CPU driver if needed
[ -f /opt/intel/opencl-1.2-4.5.0.8/etc/intel64.icd ] || {

    # Create working area
    [ -d $TMPDIR ] || {
        printinfo Creating temporary work area $TMPDIR...
        mkdir -p $TMPDIR || die Unable to create tempdir $TMPDIR
    }
    cd $TMPDIR

    # Retrieve Intel CPU OpenCL distribution tarball
    [ -f $FILENAME ] || {
        printinfo Downloading Intel CPU OpenCL driver...
        for i in 1 2 3 4 5 6 7 8 9 10; do
            curl -C - -# $URL -o $FILENAME
            RET=$?
            [ $RET -eq 0 ] && break
            # TODO: Check here if max tries, then exit
            [ $RET -eq 33 ] && printinfo Ignoring... && break    # workaround curl bug
            [ $RET -eq 56 ] && continue # network timeout
	    die Unable to download Intel CPU OpenCL driver!
        done
    }

    # Unpack outer tgz
    [ -d $DIRNM ] || {
        printinfo Unpacking driver file $FILENAME
        tar xzf $FILENAME || die Unable to unpack driver file $FILENAME!
    }

    # Unpack Intel base and CPU rpms
    [ -d $DESTDIR/opt/intel ] || {
        printinfo Unpacking Intel OpenCL driver file internal RPM files...
        cd $DESTDIR
        rpm2cpio $TMPDIR/$DIRNM/rpm/*base* | cpio -idm >/dev/null &&
        rpm2cpio $TMPDIR/$DIRNM/rpm/*cpu* | cpio -idm >/dev/null || \
            die Unable to extract Intel OpenCL driver files!
    }

    # Install Intel OCL director
    printinfo Installing Intel OpenCL dispatcher...
    update-alternatives --install /usr/lib/x86_64-linux-gnu/libOpenCL.so.1.2 libOpenCL /opt/intel/opencl-1.2-4.5.0.8/lib64/libOpenCL.so.1.2 100 || \
        die Unable to install Intel OpenCL dispatcher!
    cd /usr/lib/x86_64-linux-gnu &&
    ln -sf libOpenCL.so.1.2 libOpenCL.so.1 &&
    ln -sf libOpenCL.so.1 libOpenCL.so || die Unable to create libOpenCL.so symlinks!
    ldconfig

    # Install Intel OCL ICD
    [ -d /etc/OpenCL/vendors/intel.icd ] || {
        printinfo Installing Intel OpenCL ICD...
        mkdir -p /etc/OpenCL/vendors &&
        ln -sf /opt/intel/opencl-1.2-4.5.0.8/etc/intel64.icd /etc/OpenCL/vendors || \
            die Unable to install Intel OpenCL ICD!
    }

    # Clean up
    rm -rf $TMPDIR/$DIRNM
    rm -f $TMPDIR/$FILENAME
}

exit 0
