#!/bin/sh
set -o nounset
#set -x #DEBUG
. bin/chroot-functions.sh

# Patch out osdmo-sdr dependency in gr-osmosdr.lwr
LWR=$ROOTFS_SRCDIR/pybombs/recipes/gr-osmosdr.lwr
sed -i -e 's/\<osmo-sdr\>//g' $LWR
