#!/bin/sh
set -o nounset
#set -x #DEBUG

. bin/rootfs-library.sh

# TODO: If libtecla is a bladeRF dependency, it should go into PyBOMBS.

# Install libtecla using distro-specific package name
DIST=$(cat /etc/issue | cut -f 2 -d ' ' | cut -f 1 -d .)

if [ "$DIST" = "16" ] ; then
    printinfo Installing libtecla-dev...
    apt-get install -q -y libtecla-dev
elif [ "$DIST" = "14" ] ; then
    printinfo Installing libtecla1-dev...
    apt-get install -q -y libtecla1-dev
fi

