#!/bin/sh
set -o nounset
#set -x #DEBUG

. bin/library.sh

REMASTER_TORRENT=$REMASTER_BASE.torrent

# Exit if nothing to do
if [ $ISO_DIR/$REMASTER_TORRENT -nt $ISO_DIR/$REMASTER_NAME ] ; then exit 0; fi

printinfo Creating torrent tracker file for custom ISO image...
$BUILDTORRENT \
    -a udp://tracker.publicbt.com:80 \
    -w http://s3-dist.gnuradio.org/$REMASTER_BASE.iso,http://eu1-dist.gnuradio.org/s3/$REMASTER_BASE.iso,http://eu2-dist.gnuradio.org/$REMASTER_BASE.iso \
    $ISO_DIR/$REMASTER_NAME  \
    $ISO_DIR/$REMASTER_TORRENT

exit 0
