#!/bin/sh

set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. config/config-vars
. bin/functions.sh

# Install dpkg config file to force using "old" config files found
# during installation.
[ -f /etc/dpkg/dpkg.cfg.d/force-confold ] || {
    $PRINTINFO Enabling force-confold dpkg operation...
    install -o root -g root -m 644 \
        $CUSTOMDIR/apt/force-confold \
        /etc/dpkg/dpkg.cfg.d
}

# Install dpkg config file to prevent sync between installs (speedup)
[ -f /etc/dpkg/dpkg.cfg.d/force-unsafe-io ] || {
    $PRINTINFO Enabling force-unsafe-io dpkg operation...
    install -o root -g root -m 644 \
        $CUSTOMDIR/apt/force-unsafe-io \
        /etc/dpkg/dpkg.cfg.d
}

# Install new apt sources file for exanded repositories
[ /etc/apt/sources.list -nt $CUSTOMDIR/apt/sources.list ] || {
    $PRINTINFO Installing updated apt repository list...
    install -o root -g root -m 644 \
        $CUSTOMDIR/apt/sources.list \
        /etc/apt/
}

exit 0
