#!/bin/sh

set -o nounset
#set -x #DEBUG

cd /root/live
. config/config-vars
. bin/functions.sh

# Install dpkg config file to force using "old" config files found
# during installation.
[ -f /etc/dpkg/dpkg.cfg.d/force-confold ] || {
    $PRINTINFO Enabling force-confold dpkg operation...
    install -o root -g root -m 644 \
        /root/live/custom/apt/force-confold \
        /etc/dpkg/dpkg.cfg.d
}

exit 0
