#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. ./.config
. config/config-vars
. bin/chroot-functions.sh

# Exit if stamp file exists
[ ! -f $STAMPDIR/20-packages-02-install.stamp ] || exit 0

# Exit if nothing to do
[ -n "$(ls config/install-pkgs.d)" ] || exit 0

# Temporarily install policy file to prevent services from running
[ -f /usr/bin/policy-rc.d ] || {
    $PRINTINFO Installing temporary policy file to prevent services running...
    install -o root -g root -m 755 \
        $CUSTOMDIR/apt/policy-rc.d \
        /usr/sbin
}

# Execute each fragment in config/install-pkgs.d
$PRINTINFO Installing configured extra packages...
for pkglist in config/install-pkgs.d/*; do
    pkgs=`cat $pkglist`
    apt-get install -y $pkgs
done

# Remove policy file
$PRINTINFO Removing temporary policy-rc.d
rm -f /usr/sbin/policy-rc.d
touch $STAMPDIR/20-packages-02-install.stamp

exit 0
