#!/bin/sh

set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. ./.config
. config/config-vars
. bin/functions.sh

# Exit if stamp file exists
[ ! -f $STAMPDIR/20-packages-00-uninstall.stamp ] || exit 0

# Exit if removing packages is not configured
[ -z ${CONFIG_REMOVE_PACKAGES+x} ] || [ "$CONFIG_REMOVE_PACKAGES" != "y" ] && exit 0

# Exit if nothing to do
[ -n "$(ls config/remove-pkgs.d)" ] || exit 0

# Temporarily install policy file to prevent services from running
[ -f /usr/bin/policy-rc.d ] || {
    $PRINTINFO Installing temporary policy file to prevent services running...
    install -o root -g root -m 755 \
        $CUSTOMDIR/apt/policy-rc.d \
        /usr/sbin
}

$PRINTINFO Removing configured packages...
for pkglist in $SCRIPT_BINDDIR/config/remove-pkgs.d/*; do
    pkgs=`cat $pkglist`
    apt-get -q -q -y purge $pkgs
    apt-get -q -q -y autoremove
done

# Remove policy file
rm -f /usr/sbin/policy-rc.d

touch $STAMPDIR/20-packages-00-uninstall.stamp
$PRINTINFO Completed removing configured packages.

exit 0
