#!/bin/sh
set -o nounset
#set -x #DEBUG

cd /root/live
. config/config-vars
. bin/chroot-functions.sh

# Exit if stamp file exists
[ ! -f /root/live/stamps/20-packages-01-upgrade.stamp ] || exit 0

# Exit if upgrading packages is not configured
if [ "$UPGRADE_PKGS" != "YES" ]; then exit 0; fi

# Temporarily install policy file to prevent services from running
[ -f /usr/bin/policy-rc.d ] || {
    $PRINTINFO Installing temporary policy file to prevent services running...
    install -o root -g root -m 755 \
        /root/live/custom/apt/policy-rc.d \
        /usr/sbin
}

$PRINTINFO Upgrading packages...
apt-get update -q
apt-get upgrade -q -y

# Remove policy file
rm -f /usr/sbin/policy-rc.d

touch /root/live/stamps/20-packages-01-upgrade.stamp
$PRINTSUCCESS Completed upgrading packages.

exit 0
