#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/library.sh

# Exit if not configured
[ "${CONFIG_USE_CCACHE-x}" = "y" ] || exit 0

# Exit if stamp file exists
[ ! -f $STAMPDIR/30-ccache.stamp ] || exit 0

# Set ccache size to 20G
printinfo Configuring ccache for chroot...
CCACHE_DIR=/root/.ccache $CCACHE -M 20G

touch $STAMPDIR/30-ccache.stamp

exit 0
