#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. config/config-vars
. bin/functions.sh

# Exit if stamp file exists
[ ! -f $STAMPDIR/30-ccache.stamp ] || exit 0

# Set ccache size to 20G
if [ "$USE_CCACHE" = "YES" ] ; then
    $PRINTINFO Configuring ccache for chroot...
    CCACHE_DIR=/root/.ccache $CCACHE -M 20G
fi

touch $STAMPDIR/30-ccache.stamp

exit 0
