#!/bin/sh

cd $SCRIPT_BINDDIR

. ./.config
. config/config-vars
. bin/functions.sh

# Note: unless this is nuked from the /usr... dir, it will get
# reinstalled onto the desktop!
[ ! -f /usr/share/applications/ubuntu-amazon-default.desktop ] || {
    $PRINTINFO Nuking Amazon icon from Unity...
    rm -f /usr/share/applications/ubuntu-amazon-default.desktop
}

exit 0
