#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/chroot-library.sh

[ ! -f /etc/skel/examples.desktop ] || {
    printinfo Removing desktop examples shortcut...
    rm -f /etc/skel/examples.desktop
}

exit 0
