#!/bin/sh

cd $SCRIPT_BINDDIR
. config/config-vars
. bin/functions.sh

# Exit if already run
[ ! -f $STAMPDIR/30-desktop.stamp ] || exit 0

[ ! -f /etc/skel/examples.desktop ] || {
    $PRINTINFO Removing desktop examples shortcut...
    rm -f /etc/skel/examples.desktop
}

[ ! -f /usr/share/applications/ubuntu-amazon-default.desktop ] || {
    $PRINTINFO Nuking Amazon icon from Unity...
    rm -f /usr/share/applications/ubuntu-amazon-default.desktop
}

[ -f /etc/skel/.config/autostart/indicator-multiload.desktop ] || {
    $PRINTINFO Installing desktop autostart for indicator-multiload...
    mkdir -p /etc/skel/.config/autostart
    install -g 999 -o 999 -m 644 \
        $CUSTOMDIR/desktop/autostart/indicator-multiload.desktop \
        /etc/skel/.config/autostart
}

touch $STAMPDIR/30-desktop.stamp

exit 0
