#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/chroot-library.sh

# Exit if already run
[ ! -f $STAMPDIR/30-network.stamp ] || exit 0

# Install resolv.conf to allow resolution from inside chroot
printinfo Installing custom resolv.conf...
install -o root -g root -m 664 \
    $CUSTOMDIR/network/resolv.conf \
    /etc/

# Install network manager profiles
printinfo Installing custom Network Manager profiles...
install -o root -g root -m 400 \
    -t /etc/NetworkManager/system-connections/ \
    $CUSTOMDIR/network/NetworkManager/*

touch $STAMPDIR/30-network.stamp

exit 0
