#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/chroot-library.sh

# Exit if not configured
[ "${CONFIG_TOR_PROXY-x}" = "y" ] || exit 0

# Exit if already run
[ -f $STAMPDIR/30-tor-03-install-config.stamp ] && exit 0

# Install custom torrc
# Note: this must come after tor install for the debian-tor user to exist

printinfo Installing custom Tor configuration file...
mkdir_or_fail /etc/tor || die "Unable to create Tor configuration directory!"

install \
    -o debian-tor -g debian-tor -m 644 \
    $CUSTOMDIR/tor/torrc \
    /etc/tor || die "Unable to install Tor configuration file!"

touch $STAMPDIR/30-tor-03-install-config.stamp

exit 0
