#!/bin/sh

set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. config/config-vars
. bin/functions.sh

# Remove unneeded packages
$PRINTINFO Removing unneeded packages...
apt-get autoremove -qq -y

exit 0
