#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. ./.config
. config/config-vars
. bin/functions.sh

# Currently, only need to regen initramfs if using encrypted root
# filesystem
if [ "${CONFIG_ENCRYPT_ROOTFS-x}" != "y" ] ; then exit 0; fi

# Exit if already run once
[ ! -f $STAMPDIR/90-regen-initramfs.stamp ] || exit 0

$PRINTINFO Installing custom initrd configuration...
install -g root -o root -m 664 \
    $CUSTOMDIR/initramfs/initramfs.conf \
    /etc/initramfs-tools

$PRINTINFO Installing custom casper boot script...
if [ "${CONFIG_UBUNTU_RELEASE_TRUSTY-x}" = "y" ] ; then
    install -T -g root -o root -m 664 \
        $CUSTOMDIR/casper/casper-14.04.3 \
        /usr/share/initramfs-tools/scripts/casper
else if [ "${CONFIG_UBUNTU_RELEASE_WILY-x}" = "y" ] ; then
    install -T -g root -o root -m 664 \
        $CUSTOMDIR/casper/casper-15.10 \
        /usr/share/initramfs-tools/scripts/casper
     fi
fi

# Create new initramfs that includes cryptsetup
$PRINTINFO Creating new initramfs with crypto hooks...
export CRYPTSETUP=y
update-initramfs -k all -u || {
    $PRINTERROR Unable to execute update-initramfs!
    exit 1
}

touch $STAMPDIR/90-regen-initramfs.stamp
$PRINTSUCCESS done.

exit 0
