#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/library.sh

# Exit if already run
[ ! -f $STAMPDIR/99-clean-rootfs.stamp ] || exit 0

# Exit if nothing to do
[ -n "$(ls config/clean-rootfs.d)" ] || exit 0

# Delete each filespec in clean-rootfs.d
printinfo Deleting selected files from chroot filesystem...
for filelist in $SCRIPT_BINDDIR/config/clean-rootfs.d/*; do
    while read fs; do
        rm -rf $fs
    done < $filelist
done

# Recreate /var/log/apt/ directory
# TODO: figure out how to make this unnecessary
# Answer: truncate!
mkdir -p /var/log/apt

touch $STAMPDIR/99-clean-rootfs.stamp

exit 0
