#!/bin/sh
set -o nounset
#set -x #DEBUG

cd /root/live
. config/config-vars
. bin/functions.sh

# Exit if already run
[ ! -f stamps/99-clean-rootfs.stamp ] || exit 0

# Exit if nothing to do
[ -n "$(ls config/clean-rootfs.d)" ] || exit 0

# Delete each filespec in clean-rootfs.d
$PRINTINFO Deleting selected files from chroot filesystem...
for filelist in /root/live/config/clean-rootfs.d/*; do
    while read fs; do
        rm -rf $fs
    done < $filelist
done

# Recreate /var/log/apt/ directory
# TODO: figure out how to make this unnecessary
mkdir -p /var/log/apt

touch stamps/99-clean-rootfs.stamp

exit 0
