#!/bin/sh
set -o nounset
#set -x #DEBUG
. bin/chroot-functions.sh

# Remove compilation results
[ -d $ROOTFS_SRCDIR/pybombs/src/apache-thrift ] && {
    $PRINTINFO Removing apache-thrift build output...
    make -C $ROOTFS_SRCDIR/pybombs/src/apache-thrift distclean >/dev/null || {
        $PRINTERROR Unable to remove apache-thrift compilation files!
        exit 1
    }
}
