#!/bin/sh
set -o nounset
#set -x #DEBUG

. bin/rootfs-library.sh

# Remove compilation results
[ -d /usr/local/src/apache-thrift ] && {
    printinfo Removing apache-thrift build output...
    make -C /usr/local/src/apache-thrift distclean >/dev/null || \
        die Unable to remove apache-thrift compilation files!
}
