#!/bin/sh
set -o nounset
#set -x #DEBUG

. bin/rootfs-library.sh

printinfo Removing gnss-sdr installation binaries...
rm -f /usr/local/src/gnss-sdr/install/*

printinfo Removing gnss-sdr third party downloads...
rm -rf /usr/local/src/gnss-sdr/thirdparty/*

exit 0
