#!/bin/sh
set -o nounset
#set -x #DEBUG

. bin/chroot-functions.sh

# Install freedesktop files
[ -f /usr/share/mime/packages/gnuradio-grc.xml ] || {
    $PRINTINFO Installing GNU Radio freedesktop files...
    /usr/local/libexec/gnuradio/grc_setup_freedesktop install || {
        $PRINTERROR Unable to install gnuradio freedesktop files!
        exit 1
    }
}

# Install desktop icon for GNU Radio Companion
[ -f /etc/skel/Desktop/gnuradio-grc.desktop ] || {
    $PRINTINFO Installing GNU Radio GRC desktop shortcut...
    mkdir -p /etc/skel/Desktop
    install -g 999 -o 999 -m 644 \
        /usr/local/share/gnuradio/grc/freedesktop/gnuradio-grc.desktop \
        /etc/skel/Desktop
}

# Install live user configuration files
[ -f /etc/skel/.gnuradio/config.conf ] || {
    $PRINTINFO Installing live user configuration files...
    install -d -o 999 -g 999 /etc/skel/.gnuradio &&
    install -g 999 -o 999 -m 644 $LIVEUB_DIR/custom/gnuradio/config.conf /etc/skel/.gnuradio &&
    install -g 999 -o 999 -m 644 $LIVEUB_DIR/custom/gnuradio/thrift.conf /etc/skel/.gnuradio &&
    install -g 999 -o 999 -m 644 $LIVEUB_DIR/custom/gnuradio/.bash_aliases /etc/skel &&
    install -g 999 -o 999 -m 644 $LIVEUB_DIR/custom/gnuradio/clabs.qss /usr/local/share/gnuradio/themes &&
    install -g 999 -o 999 -m 644 $LIVEUB_DIR/custom/gnuradio/.octaverc /etc/skel || {
        $PRINTERROR Unable to install live user GNU Radio configuration files!
    }
}

# Install documentation desktop shortcut
[ -h "/etc/skel/Desktop/GNU Radio Documentation" ] || {
    $PRINTINFO Installing GNU Radio documentation shortcut...
    # FIXME automate the below versioned directory
    ln -sf /usr/local/share/doc/gnuradio-3.7.8rc1/html/index.html \
        "/etc/skel/Desktop/GNU Radio Documentation" || {
        $PRINTERROR Unable to install GNU Radio Documentation shortcut!
        exit 1
    }
}

# Install Guided tutorials
TUTDIR="/etc/skel/tutorials"
[ -d "$TUTDIR" ] || {
    mkdir -p "$TUTDIR"
    $PRINTINFO "Installing GNU Radio guided tutorials..."
    wget -q --page-requisites --convert-links --adjust-extension \
         --recursive --level=1 --no-directories \
         --no-host-directories \
         --reject-regex "history|rename|protect|edit|watch|news|issues|activity|Development|Sponsor|search|users|index|roadmap|gnuradio$|wiki$|Installing|projects$|login|register|repository|files$|gnuradio$" \
         --directory-prefix="$TUTDIR" \
         http://gnuradio.org/redmine/projects/gnuradio/wiki/Guided_Tutorials || {
        $PRINTERROR Failed to retrieve guided tutorials content!
        exit 1
    }

    cd /etc/skel/Desktop
    ln -sf "/home/ubuntu/tutorials/Guided_Tutorials.html" .
}

exit 0
