#!/bin/sh
set -o nounset
#set -x #DEBUG

. bin/rootfs-library.sh

# Install freedesktop files
[ -f /usr/share/mime/packages/gnuradio-grc.xml ] || {
    printinfo Installing GNU Radio freedesktop files...
    /usr/local/libexec/gnuradio/grc_setup_freedesktop install || \
        die Unable to install gnuradio freedesktop files!
}

# Install desktop icon for GNU Radio Companion
[ -f /etc/skel/Desktop/gnuradio-grc.desktop ] || {
    printinfo Installing GNU Radio GRC desktop shortcut...
    mkdir -p /etc/skel/Desktop
    install -g 999 -o 999 -m 644 \
        /usr/local/share/gnuradio/grc/freedesktop/gnuradio-grc.desktop \
        /etc/skel/Desktop
}

exit 0
