#!/bin/sh
set -o nounset
#set -x #DEBUG

. bin/rootfs-library.sh

# Install udev permissions for hackrf
[ -f /etc/udev/rules.d/53-hackrf.rules ] || {
    printinfo Installing udev permissions for hackrf...
    install -g root -o root -m 644 \
        /usr/local/src/hackrf/host/libhackrf/53-hackrf.rules \
        /etc/udev/rules.d || die Unable to install hackrf udev rules file!
}

# Download and install hackrf firmware files
HACKRF_VERSION=2015.07.2
[ -f /usr/local/share/hackrf/firmware-bin/hackrf_one_usb_ram.dfu ] || {
    # Download hackrf release package
    printinfo Downloading hackrf release package
    mkdir -p /tmp/hackrf &&
    curl -L -# https://github.com/mossmann/hackrf/releases/download/v$HACKRF_VERSION/hackrf-$HACKRF_VERSION.tar.xz \
        -o /tmp/hackrf/hackrf-$HACKRF_VERSION.tar.xz || die Unable to download hackrf release package!

    # Unpack release package file to tmpdir
    printinfo Unpacking hackrf release package...
    cd /tmp/hackrf &&
    tar xf hackrf-$HACKRF_VERSION.tar.xz || die Unable to unpack hackrf firmware!

    # Install firmware-bin files
    printinfo Installing hackrf firmware files...
    TMPDIR=/tmp/hackrf/hackrf-$HACKRF_VERSION/firmware-bin
    DESTDIR=/usr/local/share/hackrf/firmware-bin

    mkdir -p $DESTDIR &&
    install -o root -g root -m 644 \
        -t $DESTDIR \
        $TMPDIR/hackrf_cpld_default.xsvf \
        $TMPDIR/hackrf_jawbreaker_usb_ram.dfu \
        $TMPDIR/hackrf_jawbreaker_usb_rom_to_ram.bin \
        $TMPDIR/hackrf_one_usb_ram.dfu \
        $TMPDIR/hackrf_one_usb_rom_to_ram.bin || die Unable to install hackrf firmware files!

    cd - >/dev/null
    rm -rf /tmp/hackrf
}

# Download, compile, and install dfu-util
DFU_UTIL_VERSION=0.7
[ -x /usr/local/bin/dfu-util ] || {
    printinfo Downloading dfu-util-$DFU_UTIL_VERSION...
    # Download source tarball
    mkdir -p /tmp/hackrf &&
    curl -# http://dfu-util.sourceforge.net/releases/dfu-util-$DFU_UTIL_VERSION.tar.gz \
        -o /tmp/hackrf/dfu-util-$DFU_UTIL_VERSION.tar.gz || \
    die Unable to download dfu-util-$DFU_UTIL_VERSION!

    # Unpack source tarball
    printinfo Unpacking dfu-util-$DFU_UTIL_VERSION source tarball...
    cd /tmp/hackrf &&
    tar xzf dfu-util-$DFU_UTIL_VERSION.tar.gz || die Unable to unpack hackrf firmware!

    # Compile and install source tarball
    printinfo Compiling dfu-util-$DFU_UTIL_VERSION...
    cd /tmp/hackrf/dfu-util-$DFU_UTIL_VERSION &&
    ./configure --prefix=/usr/local &&
    make &&
    make install || die Unable to compile/install dfu-util $DFU_UTIL_VERSION!

    cd - >/dev/null
    rm -rf /tmp/hackrf
}
