#!/bin/sh
set -o nounset
#set -x #DEBUG
. bin/chroot-functions.sh

# Install udev permissions for hackrf
[ -f /etc/udev/rules.d/53-hackrf.rules ] || {
    $PRINTINFO Installing udev permissions for hackrf...
    install -g root -o root -m 644 \
        $ROOTFS_SRCDIR/pybombs/src/hackrf/host/libhackrf/53-hackrf.rules \
        /etc/udev/rules.d || {
        $PRINTERROR Unable to install hackrf udev rules file!
        exit 1
    }
}

# Download and install hackrf firmware files
[ -f /usr/local/share/hackrf/firmware-bin/hackrf_one_usb_ram.dfu ] || {
    # Download hackrf release package
    $PRINTINFO Downloading hackrf release package
    mkdir -p /tmp/hackrf &&
    curl -# http://iweb.dl.sourceforge.net/project/hackrf/hackrf-2014.08.1.tar.xz \
        -o /tmp/hackrf/hackrf-2014.08.1.tar.xz || {
        $PRINTERROR Unable to download hackrf release package!
        exit 1
    }

    # Unpack release package file to tmpdir
    $PRINTINFO Unpacking hackrf release package...
    cd /tmp/hackrf &&
    tar xJf hackrf-2014.08.1.tar.xz || {
        $PRINTERROR Unable to unpack hackrf firmware!
        exit 1
    }

    # Install firmware-bin files
    $PRINTINFO Installing hackrf firmware files...
    TMPDIR=/tmp/hackrf/hackrf-2014.08.1/firmware-bin
    DESTDIR=/usr/local/share/hackrf/firmware-bin

    mkdir -p $DESTDIR &&
    install -o root -g root -m 644 \
        -t $DESTDIR \
        $TMPDIR/hackrf_cpld_default.xsvf \
        $TMPDIR/hackrf_jawbreaker_usb_ram.dfu \
        $TMPDIR/hackrf_jawbreaker_usb_rom_to_ram.bin \
        $TMPDIR/hackrf_one_usb_ram.dfu \
        $TMPDIR/hackrf_one_usb_rom_to_ram.bin || {
        $PRINTERROR Unable to install hackrf firmware files!
    }

    cd - >/dev/null
    rm -rf /tmp/hackrf
}

# Download, compile, and install dfu-util 0.5
[ -x /usr/local/bin/dfu-util ] || {
    $PRINTINFO Downloading dfu-util-0.5...
    # Download source tarball
    mkdir -p /tmp/hackrf &&
    curl -# http://dfu-util.sourceforge.net/releases/dfu-util-0.5.tar.gz \
        -o /tmp/hackrf/dfu-util-0.5.tar.gz || {
        $PRINTERROR Unable to download dfu-util-0.5!
        exit 1
    }

    # Unpack source tarball
    $PRINTINFO Unpacking dfu-util-0.5 source tarball...
    cd /tmp/hackrf &&
    tar xzf dfu-util-0.5.tar.gz || {
        $PRINTERROR Unable to unpack hackrf firmware!
        exit 1
    }

    # Compile and install source tarball
    $PRINTINFO Compiling dfu-util-0.5...
    cd /tmp/hackrf/dfu-util-0.5 &&
    ./configure --prefix=/usr/local &&
    make &&
    make install || {
        $PRINTERROR Unable to compile/install dfu-util 0.5!
        exit 1
    }

    cd - >/dev/null
    rm -rf /tmp/hackrf
}
