#!/bin/sh
set -o nounset
#set -x #DEBUG
. bin/chroot-functions.sh

# Install udev permissions for rtl-sdr
[ -x /etc/udev/rules.d/rtl-sdr.rules ] || {
    install -g root -o root -m 644 \
        $ROOTFS_SRCDIR/pybombs/src/rtl-sdr/rtl-sdr.rules \
        /etc/udev/rules.d || {
        $PRINTERROR Unable to install rtl-sdr udev rules file!
        exit 1
    }
}

exit 0
