#!/bin/sh
set -o nounset
#set -x #DEBUG

. bin/rootfs-library.sh

# Install udev permissions for rtl-sdr
[ -x /etc/udev/rules.d/rtl-sdr.rules ] || {
    install -g root -o root -m 644 \
        /usr/local/src/rtl-sdr/rtl-sdr.rules \
        /etc/udev/rules.d || die Unable to install rtl-sdr udev rules file!
}

exit 0
