#!/bin/sh
set -o nounset
#set -x #DEBUG

. bin/rootfs-library.sh

# Install the udev rules file
[ -f /etc/udev/rules.d/uhd-usrp.rules ] || {
    printinfo Installing UHD udev rules file...
    install -g root -o root -m 644 /usr/local/src/uhd/host/utils/uhd-usrp.rules /etc/udev/rules.d || \
        die Unable to install UHD udev rules file!
}

refresh_or_install_file \
    /etc/sysctl.d/10-uhd-buffers.conf \
    "Installing UHD sysctl params..."

refresh_or_install_file \
    /etc/security/limits.d/10-uhd-limits.conf \
    "Installing UHD limits file..."

# Download and install firmware images
[ -f /usr/local/share/uhd/images/LICENSE ] || {
    printinfo Installing UHD firmware images...
    uhd_images_downloader || die Unable to download UHD firmware images!
}

exit 0
