#!/bin/sh
set -o nounset
#set -x #DEBUG

. config/config-vars
. bin/functions.sh

require_rootfs_rw_mounted

echo Enabling force-confold dpkg operation...
$SUDO install -o root -g root -m 644 \
    custom/apt/force-confold \
    $ROOTFSMNT_RW/etc/dpkg/dpkg.cfg.d

exit 0
