#!/bin/sh
set -o nounset
#set -x #DEBUG

. config/config-vars
. bin/functions.sh

require_rootfs_rw_mounted

$PRINTINFO Installing custom APT sources.list...
$SUDO install -o root -g root -m 644 \
    custom/apt/sources.list \
    $ROOTFSMNT_RW/etc/apt/sources.list

$PRINTINFO Enabling force-unsafe-io dpkg operation...
$SUDO install -o root -g root -m 644 \
    custom/apt/force-unsafe-io \
    $ROOTFSMNT_RW/etc/dpkg/dpkg.cfg.d

$PRINTINFO Enabling force-confold dpkg operation...
$SUDO install -o root -g root -m 644 \
    custom/apt/force-confold \
    $ROOTFSMNT_RW/etc/dpkg/dpkg.cfg.d

exit 0
