#!/bin/sh
set -o nounset
#set -x #DEBUG

. config/config-vars
. bin/functions.sh

if [ "$USE_CCACHE" = "YES" ] ; then
    $PRINTINFO Configuring ccache for chroot...
    CCACHE_DIR=./ccache $CCACHE -M 20G
fi

exit 0
