#!/bin/sh

$PRINTINFO Removing desktop examples shortcut...
sudo rm -f $ROOTFSMNT_RW/etc/skel/examples.desktop

$PRINTINFO Nuking Amazon icon from Unity...
sudo rm -f $ROOTFSMNT_RW/usr/share/applications/ubuntu-amazon-default.desktop

$PRINTINFO Installing desktop autostart for indicator-multiload...
sudo mkdir -p $ROOTFSMNT_RW/etc/skel/.config/autostart
sudo install -g 999 -o 999 -m 644 \
    custom/desktop/autostart/indicator-multiload.desktop \
    $ROOTFSMNT_RW/etc/skel/.config/autostart
