#!/bin/sh
set -o nounset
#set -x #DEBUG

. config/config-vars
. bin/functions.sh

$PRINTINFO Creating linux-tools symbolic link...
$SUDO ln -sf /usr/lib/linux-tools/3.16.0-30-generic/perf $ROOTFSMNT_RW/usr/local/bin/

# Allows user to to run perf, but segfaults
#
#$PRINTINFO Installing kernel configuration file for linux-tools...
#$SUDO install -g root -o root -m 644 \
#    custom/linux-tools/10-linux-tools.conf \
#    $ROOTFSMNT_RW/etc/sysctl.d

exit 0
