#!/bin/sh
set -o nounset
#set -x #DEBUG

. config/config-vars
. bin/functions.sh

$PRINTINFO Installing custom Unity low graphics mode config
$SUDO install -m 644 \
    custom/unity/ubuntu.session \
    $ROOTFSMNT_RW/usr/share/gnome-session/sessions/
$SUDO install -m 644 \
    custom/unity/unity7.conf \
    $ROOTFSMNT_RW/usr/share/upstart/sessions/unity7.conf

exit 0
