#!/bin/sh
set -o nounset
#set -x #DEBUG

. config/config-vars
. bin/functions.sh

require_rootfs_rw_mounted

$PRINTINFO Installing custom isolinux menu configuration...
$SUDO mkdir -p $ISOMNT_RW/isolinux
$SUDO install -g root -o root -m 664 \
    custom/casper/txt.cfg \
    $ISOMNT_RW/isolinux

exit 0
