#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

refresh_or_install_file \
    /etc/dpkg/dpkg.cfg.d/force-unsafe-io \
    "Disabling dpkg fsync between packages..."

exit 0
