#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

refresh_or_install_file \
    /etc/dpkg/dpkg.cfg.d/force-confold \
    "Forcing dpkg to not overwrite conffiles..."

exit 0
