#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

# Exit if nothing to do
exit_if_not_configured CONFIG_UPGRADE_PACKAGES
exit_if_stamped $0

# Temporarily install policy file to prevent services from running
prevent_services_running
export DEBIAN_FRONTEND=noninteractive

if [ "${CONFIG_UBUNTU_RELEASE_WILY-x}" = "y" ] ; then
    # HACK HACK HACK
    # See https://bugs.launchpad.net/y-ppa-manager/+bug/1464440
    printinfo Unfscking wacom package for upgrade...
    rm -r /lib/udev/rules.d/69-wacom*
    rm -r /lib/systemd/system/wacom-inputattach\@.service
fi

printinfo Upgrading packages...
apt-get update
apt-get upgrade -y

allow_services_to_run
make_stamp $0
printsuccess Completed upgrading packages.

exit 0
