#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

# Exit if upgrading packages is not configured
[ -z ${CONFIG_UPGRADE_PACKAGES+x} ] || [ "$CONFIG_UPGRADE_PACKAGES" != "y" ] && exit 0

# Exit if stamp file exists
[ ! -f $STAMPDIR/20-packages-01-upgrade.stamp ] || exit 0

# Temporarily install policy file to prevent services from running
[ -f /usr/bin/policy-rc.d ] || {
    printinfo Installing temporary policy file to prevent services running...
    install -o root -g root -m 755 \
        $CUSTOMDIR/apt/policy-rc.d \
        /usr/sbin
}

# Prevent user prompts
export DEBIAN_FRONTEND=noninteractive

if [ "${CONFIG_UBUNTU_RELEASE_WILY-x}" = "y" ] ; then
    # HACK HACK HACK
    # See https://bugs.launchpad.net/y-ppa-manager/+bug/1464440
    printinfo Unfscking wacom package for upgrade...
    rm -r /lib/udev/rules.d/69-wacom*
    rm -r /lib/systemd/system/wacom-inputattach\@.service
fi

printinfo Upgrading packages...
apt-get update
apt-get upgrade -y

# Remove policy file
rm -f /usr/sbin/policy-rc.d

touch $STAMPDIR/20-packages-01-upgrade.stamp
printsuccess Completed upgrading packages.

exit 0
