#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

# Note: unless this is nuked from the /usr... dir, it will get
# reinstalled onto the desktop!
[ ! -f /usr/share/applications/ubuntu-amazon-default.desktop ] || {
    printinfo Nuking Amazon icon from Unity...
    rm -f /usr/share/applications/ubuntu-amazon-default.desktop

    updated_rootfs
}

exit 0
