#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

[ -f /etc/skel/.config/autostart/indicator-multiload.desktop ] || {
    printinfo Installing desktop autostart for indicator-multiload...
    mkdir -p /etc/skel/.config/autostart
    install -g 999 -o 999 -m 644 \
        $CUSTOMDIR/desktop/autostart/indicator-multiload.desktop \
        /etc/skel/.config/autostart
}

exit 0
