#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

# TODO: make kconfig option

refresh_or_install_file_as \
    ferm.conf.workstation \
    /etc/ferm/ferm.conf \
    "Installing ferm firewall configuration..."

exit 0
