#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

# Exit if not configured
[ "${CONFIG_TOR_PROXY-x}" = "y" ] || exit 0

# Exit if already run
[ -f $STAMPDIR/30-tor-00-install-tor-key.stamp ] && exit 0

TOR_KEY_ID=886DDD89
GPG=/usr/bin/gpg
APT_KEYRING=/etc/apt/trusted.gpg

# Import torproject.org deb signing key
printinfo Check for torproject.org gpg public key $TOR_KEY_ID...
$GPG --list-keys $TOR_KEY_ID >/dev/null || {
    printinfo Not found, retrieving for import into keyring...
    $GPG --keyserver keys.gnupg.net --recv-keys $TOR_KEY_ID || die Import of key failed!
    printsuccess Import successful.
}

# Add key to chroot apt-key keyring
apt-key --keyring $APT_KEYRING list | grep -q $TOR_KEY_ID || {
    printinfo Installing torproject.org public key into chroot apt-key keyring...
    $GPG --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | apt-key --keyring $APT_KEYRING add - || \
        die Failed to import key into apt-key keyring!
}

touch $STAMPDIR/30-tor-00-install-tor-key.stamp

exit 0
