#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

# Exit if not configured
[ "${CONFIG_TOR_PROXY-x}" = "y" ] || exit 0

# Exit if already run
[ -f $STAMPDIR/30-tor-02-install-apps.stamp ] && exit 0

# Update repositories and install
# Temporarily install policy file to prevent services from running
[ -f /usr/bin/policy-rc.d ] || {
    printinfo Installing temporary policy file to prevent services running...
    install -o root -g root -m 755 \
        $CUSTOMDIR/apt/policy-rc.d \
        /usr/sbin
}

apt-get install -q -q -y tor tor-arm || die "Unable to install Tor applications!"

# Remove policy file
rm -f /usr/sbin/policy-rc.d

touch $STAMPDIR/30-tor-02-install-apps.stamp

exit 0
