#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

refresh_or_install_file \
    /usr/share/gnome-session/sessions/ubuntu.session \
    "Installing custom Unity low graphics mode session..."

refresh_or_install_file \
    /usr/share/upstart/sessions/unity7.conf \
    "Installing custom Unity upstart configuration..."

exit 0
