#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

# Exit if already run
#[ ! -f $STAMPDIR/30-unity-disable-scopes.stamp ] || exit 0

printinfo "Disabling Unity remote scopes..."
dbus-launch --exit-with-session gsettings set com.canonical.Unity.Lenses remote-content-search none &&
dbus-launch --exit-with-session gsettings set com.canonical.Unity.Lenses disabled-scopes \
      "['more_suggestions-amazon.scope', 'more_suggestions-u1ms.scope',
      'more_suggestions-populartracks.scope', 'music-musicstore.scope',
      'more_suggestions-ebay.scope', 'more_suggestions-ubuntushop.scope',
      'more_suggestions-skimlinks.scope']" || die "Unable to disable remote scopes!"

if ! grep -q productsearch.ubuntu.com /etc/hosts; then
    printinfo "Disabling Unity Dash keystroke spying..."
    echo "127.0.0.1 productsearch.ubuntu.com" >> /etc/hosts
fi;

#touch $STAMPDIR/30-unity-disable-scopes.stamp

exit 0
