#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

# Exit if already run
[ ! -f $STAMPDIR/30-unity.stamp ] || exit 0

[ /usr/share/gnome-session/sessions/ubuntu.session -nt \
  $CUSTOMDIR/unity/ubuntu.session ] || {
    printinfo Installing custom Unity low graphics mode configuration...
    install -m 644 \
        $CUSTOMDIR/unity/ubuntu.session \
        /usr/share/gnome-session/sessions/

    install -m 644 \
        $CUSTOMDIR/unity/unity7.conf \
        /usr/share/upstart/sessions/unity7.conf
}

touch $STAMPDIR/30-unity.stamp

exit 0
