#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

refresh_or_install_file \
    /etc/skel/.gnuradio/config.conf \
    "Installing GNU Radio configuration file..."

refresh_or_install_file \
    /etc/skel/.gnuradio/thrift.conf \
    "Installing Apache thrift configuration file..."

exit 0
