#!/bin/sh
set -o nounset
#set -x #DEBUG

cd $SCRIPT_BINDDIR
. bin/rootfs-library.sh

# Exit if already run
[ ! -f $STAMPDIR/40-gnuradio-desktop.stamp ] || exit 0

printinfo Installing GNU Radio logo file...
mkdir -p /usr/local/share/gnuradio
install -g root -o root -m 644 \
    $CUSTOMDIR/gnuradio/gnuradio_logo.png \
    /usr/local/share/gnuradio

printinfo Installing custom Mozilla profile...
cp -a $CUSTOMDIR/desktop/firefox/.mozilla \
    /etc/skel
chown 999.999 -R /etc/skel/.mozilla

printinfo Installing home directory shortcuts...
ln -sf /usr/local/src/pybombs/src /etc/skel
ln -sf /usr/local/share/gnuradio/examples /etc/skel

touch $STAMPDIR/40-gnuradio-desktop.stamp

exit 0
